/*
  3.1 스칼라 데이터 타입
   - 일반 단일 데이터타입 변수 , %Type 데이터형 변수
   
   3.2 복합데이터 타입
   
*/

Select *  from ALL_TAB_COLUMNS where TABLE_NAME = 'USERS';
SELECT * FROM USERS;

CREATE OR REPLACE PROCEDURE USERS_PRINT
(P_ID IN USERS.ID%TYPE)
IS
--%TYPE 데이터형 변수 선언
V_ID USERS.ID%TYPE;
V_NAME USERS.NAME%TYPE;
V_PASSWORD USERS.PASSWORD%TYPE;
V_EMAIL USERS.EMAIL%TYPE;

BEGIN
 
 DBMS_OUTPUT.ENABLE;
 
 --%TYPE 데이터형 변수 사용
 SELECT ID,NAME,PASSWORD, EMAIL
 INTO V_ID,V_NAME,V_PASSWORD, V_EMAIL
 FROM   USERS
 WHERE ID = P_ID;
 
 --결과값 출력
 DBMS_OUTPUT.PUT_LINE('ID : ' || V_ID);
 DBMS_OUTPUT.PUT_LINE('NAME : ' || V_NAME);
 DBMS_OUTPUT.PUT_LINE('PASSWORD : ' || V_PASSWORD);
 DBMS_OUTPUT.PUT_LINE('EMAIL : ' || V_EMAIL);
 END;
/
-- DBMS_OUTPUT 결과값을 화면에 출력하기 위해
SET SERVEROUTPUT ON;
EXECUTE USERS_PRINT('green');






